name: Furby default jobs
on: push
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - run: go test -v ./... -bench=.